window.CHARACTERS = [
  {
    "id": "fai",
    "name": "Fai",
    "role": "ATTACK",
    "attack_type": "ATTACK",
    "base_attack": 1500,
    "base_defense": 571,
    "base_hp": 3326,
    "base_speed": 29,
    "transcend_primary": "ATK",
    "star4_bonus": "CR",
    "grade": "LEGEND"
  },
  {
    "id": "sorun",
    "name": "Sorun",
    "role": "ATTACK",
    "attack_type": "ATTACK",
    "base_attack": 1712,
    "base_defense": 668,
    "base_hp": 3836,
    "base_speed": 29,
    "transcend_primary": "ATK",
    "star4_bonus": "CR",
    "grade": "LEGEND"
  },
  {
    "id": "kyle",
    "name": "Kyle",
    "role": "ATTACK",
    "attack_type": "ATTACK",
    "base_attack": 1500,
    "base_defense": 571,
    "base_hp": 3326,
    "base_speed": 29,
    "transcend_primary": "ATK",
    "star4_bonus": "CR",
    "grade": "LEGEND"
  },
  {
    "id": "karl_heron",
    "name": "Karl Heron",
    "role": "ATTACK",
    "attack_type": "ATTACK",
    "base_attack": 1500,
    "base_defense": 571,
    "base_hp": 3326,
    "base_speed": 29,
    "transcend_primary": "ATK",
    "star4_bonus": "CR",
    "grade": "LEGEND"
  },
  {
    "id": "branze_bransel",
    "name": "Branze & Bransel",
    "role": "ATTACK",
    "attack_type": "ATTACK",
    "base_attack": 1500,
    "base_defense": 571,
    "base_hp": 3326,
    "base_speed": 29,
    "transcend_primary": "ATK",
    "star4_bonus": "CR",
    "grade": "LEGEND"
  },
  {
    "id": "kagura",
    "name": "Kagura",
    "role": "ATTACK",
    "attack_type": "ATTACK",
    "base_attack": 1500,
    "base_defense": 571,
    "base_hp": 3326,
    "base_speed": 29,
    "transcend_primary": "ATK",
    "star4_bonus": "EFF",
    "grade": "LEGEND"
  },
  {
    "id": "lubu",
    "name": "Lubu",
    "role": "ATTACK",
    "attack_type": "ATTACK",
    "base_attack": 1500,
    "base_defense": 571,
    "base_hp": 3326,
    "base_speed": 29,
    "transcend_primary": "ATK",
    "star4_bonus": "WK",
    "grade": "LEGEND"
  },
  {
    "id": "ryan",
    "name": "Ryan",
    "role": "ATTACK",
    "attack_type": "ATTACK",
    "base_attack": 1500,
    "base_defense": 571,
    "base_hp": 3326,
    "base_speed": 29,
    "transcend_primary": "ATK",
    "star4_bonus": "CR",
    "grade": "LEGEND"
  },
  {
    "id": "klahan",
    "name": "Klahan",
    "role": "ATTACK",
    "attack_type": "ATTACK",
    "base_attack": 1500,
    "base_defense": 571,
    "base_hp": 3326,
    "base_speed": 29,
    "transcend_primary": "ATK",
    "star4_bonus": "CR",
    "grade": "LEGEND"
  },
  {
    "id": "colt",
    "name": "Colt",
    "role": "ATTACK",
    "attack_type": "ATTACK",
    "base_attack": 1500,
    "base_defense": 571,
    "base_hp": 3326,
    "base_speed": 29,
    "transcend_primary": "ATK",
    "star4_bonus": "EFF",
    "grade": "LEGEND"
  },
  {
    "id": "teo",
    "name": "Teo",
    "role": "ATTACK",
    "attack_type": "ATTACK",
    "base_attack": 1500,
    "base_defense": 571,
    "base_hp": 3326,
    "base_speed": 29,
    "transcend_primary": "ATK",
    "star4_bonus": "CDM",
    "grade": "LEGEND"
  },
  {
    "id": "dellons",
    "name": "Dellons",
    "role": "ATTACK",
    "attack_type": "ATTACK",
    "base_attack": 1500,
    "base_defense": 571,
    "base_hp": 3326,
    "base_speed": 29,
    "transcend_primary": "ATK",
    "star4_bonus": "CR",
    "grade": "LEGEND"
  },
  {
    "id": "taka",
    "name": "Taka",
    "role": "ATTACK",
    "attack_type": "ATTACK",
    "base_attack": 1500,
    "base_defense": 571,
    "base_hp": 3326,
    "base_speed": 29,
    "transcend_primary": "ATK",
    "star4_bonus": "CR",
    "grade": "LEGEND"
  },
  {
    "id": "shane",
    "name": "Shane",
    "role": "ATTACK",
    "attack_type": "ATTACK",
    "base_attack": 1500,
    "base_defense": 571,
    "base_hp": 3326,
    "base_speed": 29,
    "transcend_primary": "ATK",
    "star4_bonus": "CR",
    "grade": "LEGEND"
  },
  {
    "id": "ballista",
    "name": "Ballista",
    "role": "ATTACK",
    "attack_type": "ATTACK",
    "base_attack": 1500,
    "base_defense": 571,
    "base_hp": 3326,
    "base_speed": 29,
    "transcend_primary": "ATK",
    "star4_bonus": "CR",
    "grade": "LEGEND"
  },
  {
    "id": "bi_dam",
    "name": "Bi Dam",
    "role": "ATTACK",
    "attack_type": "ATTACK",
    "base_attack": 1500,
    "base_defense": 571,
    "base_hp": 3326,
    "base_speed": 29,
    "transcend_primary": "ATK",
    "star4_bonus": "CR",
    "grade": "LEGEND"
  },
  {
    "id": "amelia",
    "name": "Amelia",
    "role": "ATTACK",
    "attack_type": "ATTACK",
    "base_attack": 1500,
    "base_defense": 571,
    "base_hp": 3326,
    "base_speed": 29,
    "transcend_primary": "ATK",
    "star4_bonus": "CR",
    "grade": "LEGEND"
  },
  {
    "id": "bai_long",
    "name": "Bai Long",
    "role": "ATTACK",
    "attack_type": "ATTACK",
    "base_attack": 1500,
    "base_defense": 571,
    "base_hp": 3326,
    "base_speed": 29,
    "transcend_primary": "ATK",
    "star4_bonus": "CR",
    "grade": "LEGEND"
  },
  {
    "id": "randgrid",
    "name": "Randgrid",
    "role": "ATTACK",
    "attack_type": "ATTACK",
    "base_attack": 1500,
    "base_defense": 571,
    "base_hp": 3326,
    "base_speed": 29,
    "transcend_primary": "ATK",
    "star4_bonus": "WK",
    "grade": "LEGEND"
  },
  {
    "id": "cha_hae_in",
    "name": "Cha Hae-in",
    "role": "ATTACK",
    "attack_type": "ATTACK",
    "base_attack": 1500,
    "base_defense": 571,
    "base_hp": 3326,
    "base_speed": 29,
    "transcend_primary": "ATK",
    "star4_bonus": "CR",
    "grade": "LEGEND"
  },
  {
    "id": "deo",
    "name": "Deo",
    "role": "ATTACK",
    "attack_type": "ATTACK",
    "base_attack": 1500,
    "base_defense": 571,
    "base_hp": 3326,
    "base_speed": 29,
    "transcend_primary": "ATK",
    "star4_bonus": "CR",
    "grade": "LEGEND"
  },
  {
    "id": "heavenia",
    "name": "Heavenia",
    "role": "ATTACK",
    "attack_type": "ATTACK",
    "base_attack": 1389,
    "base_defense": 533,
    "base_hp": 3174,
    "base_speed": 25,
    "transcend_primary": "ATK",
    "star4_bonus": "CR",
    "grade": "RARE"
  },
  {
    "id": "feng_yan",
    "name": "Feng Yan",
    "role": "ATTACK",
    "attack_type": "ATTACK",
    "base_attack": 1389,
    "base_defense": 533,
    "base_hp": 3174,
    "base_speed": 25,
    "transcend_primary": "ATK",
    "star4_bonus": "CR",
    "grade": "RARE"
  },
  {
    "id": "soi",
    "name": "Soi",
    "role": "ATTACK",
    "attack_type": "ATTACK",
    "base_attack": 1389,
    "base_defense": 533,
    "base_hp": 3174,
    "base_speed": 25,
    "transcend_primary": "ATK",
    "star4_bonus": "CR",
    "grade": "RARE"
  },
  {
    "id": "snipper",
    "name": "Snipper",
    "role": "ATTACK",
    "attack_type": "ATTACK",
    "base_attack": 1389,
    "base_defense": 533,
    "base_hp": 3174,
    "base_speed": 25,
    "transcend_primary": "ATK",
    "star4_bonus": "CR",
    "grade": "RARE"
  },
  {
    "id": "jupy",
    "name": "Jupy",
    "role": "ATTACK",
    "attack_type": "ATTACK",
    "base_attack": 1389,
    "base_defense": 533,
    "base_hp": 3174,
    "base_speed": 25,
    "transcend_primary": "ATK",
    "star4_bonus": "CR",
    "grade": "RARE"
  },
  {
    "id": "jane",
    "name": "Jane",
    "role": "ATTACK",
    "attack_type": "ATTACK",
    "base_attack": 1389,
    "base_defense": 533,
    "base_hp": 3174,
    "base_speed": 25,
    "transcend_primary": "ATK",
    "star4_bonus": "EFF",
    "grade": "RARE"
  },
  {
    "id": "may",
    "name": "May",
    "role": "ATTACK",
    "attack_type": "ATTACK",
    "base_attack": 1389,
    "base_defense": 533,
    "base_hp": 3174,
    "base_speed": 25,
    "transcend_primary": "ATK",
    "star4_bonus": "EFF",
    "grade": "RARE"
  },
  {
    "id": "black_rose",
    "name": "Black Rose",
    "role": "ATTACK",
    "attack_type": "ATTACK",
    "base_attack": 1389,
    "base_defense": 533,
    "base_hp": 3174,
    "base_speed": 25,
    "transcend_primary": "ATK",
    "star4_bonus": "CR",
    "grade": "RARE"
  },
  {
    "id": "catty",
    "name": "Catty",
    "role": "ATTACK",
    "attack_type": "ATTACK",
    "base_attack": 1389,
    "base_defense": 533,
    "base_hp": 3174,
    "base_speed": 25,
    "transcend_primary": "ATK",
    "star4_bonus": "CR",
    "grade": "RARE"
  },
  {
    "id": "jin",
    "name": "Jin",
    "role": "ATTACK",
    "attack_type": "ATTACK",
    "base_attack": 1389,
    "base_defense": 533,
    "base_hp": 3174,
    "base_speed": 25,
    "transcend_primary": "ATK",
    "star4_bonus": "CR",
    "grade": "RARE"
  },
  {
    "id": "ray",
    "name": "Ray",
    "role": "ATTACK",
    "attack_type": "ATTACK",
    "base_attack": 1389,
    "base_defense": 533,
    "base_hp": 3174,
    "base_speed": 25,
    "transcend_primary": "ATK",
    "star4_bonus": "CR",
    "grade": "RARE"
  },
  {
    "id": "zhao_yun",
    "name": "Zhao Yun",
    "role": "ATTACK",
    "attack_type": "ATTACK",
    "base_attack": 1389,
    "base_defense": 533,
    "base_hp": 3174,
    "base_speed": 25,
    "transcend_primary": "ATK",
    "star4_bonus": "CR",
    "grade": "RARE"
  },
  {
    "id": "leo",
    "name": "Leo",
    "role": "ATTACK",
    "attack_type": "ATTACK",
    "base_attack": 1389,
    "base_defense": 533,
    "base_hp": 3174,
    "base_speed": 25,
    "transcend_primary": "ATK",
    "star4_bonus": "CR",
    "grade": "RARE"
  },
  {
    "id": "hokin",
    "name": "Hokin",
    "role": "ATTACK",
    "attack_type": "ATTACK",
    "base_attack": 1389,
    "base_defense": 533,
    "base_hp": 3174,
    "base_speed": 25,
    "transcend_primary": "ATK",
    "star4_bonus": "CR",
    "grade": "RARE"
  },
  {
    "id": "xiao",
    "name": "Xiao",
    "role": "ATTACK",
    "attack_type": "ATTACK",
    "base_attack": 1389,
    "base_defense": 533,
    "base_hp": 3174,
    "base_speed": 25,
    "transcend_primary": "ATK",
    "star4_bonus": "CR",
    "grade": "RARE"
  },
    {
    "id": "yeonhee",
    "name": "Yeonhee",
    "role": "MAGIC",
    "attack_type": "MAGIC",
    "base_attack": 1500,
    "base_defense": 571,
    "base_hp": 3326,
    "base_speed": 29,
    "transcend_primary": "ATK",
    "star4_bonus": "CR",
    "grade": "LEGEND"
  },
  {
    "id": "spike",
    "name": "Spike",
    "role": "MAGIC",
    "attack_type": "MAGIC",
    "base_attack": 1500,
    "base_defense": 571,
    "base_hp": 3326,
    "base_speed": 29,
    "transcend_primary": "ATK",
    "star4_bonus": "CR",
    "grade": "LEGEND"
  },
  {
    "id": "ace",
    "name": "Ace",
    "role": "MAGIC",
    "attack_type": "MAGIC",
    "base_attack": 1500,
    "base_defense": 571,
    "base_hp": 3326,
    "base_speed": 29,
    "transcend_primary": "ATK",
    "star4_bonus": "CR",
    "grade": "LEGEND"
  },
  {
    "id": "rin",
    "name": "Rin",
    "role": "MAGIC",
    "attack_type": "MAGIC",
    "base_attack": 1500,
    "base_defense": 571,
    "base_hp": 3326,
    "base_speed": 29,
    "transcend_primary": "ATK",
    "star4_bonus": "CR",
    "grade": "LEGEND"
  },
  {
    "id": "sun_wukong",
    "name": "Sun Wukong",
    "role": "MAGIC",
    "attack_type": "MAGIC",
    "base_attack": 1500,
    "base_defense": 571,
    "base_hp": 3326,
    "base_speed": 29,
    "transcend_primary": "ATK",
    "star4_bonus": "CR",
    "grade": "LEGEND"
  },
  {
    "id": "melcure",
    "name": "Melcure",
    "role": "MAGIC",
    "attack_type": "MAGIC",
    "base_attack": 1500,
    "base_defense": 571,
    "base_hp": 3326,
    "base_speed": 29,
    "transcend_primary": "ATK",
    "star4_bonus": "EFF",
    "grade": "LEGEND"
  },
  {
    "id": "freyja",
    "name": "Freyja",
    "role": "MAGIC",
    "attack_type": "MAGIC",
    "base_attack": 1500,
    "base_defense": 571,
    "base_hp": 3326,
    "base_speed": 29,
    "transcend_primary": "ATK",
    "star4_bonus": "CR",
    "grade": "LEGEND"
  },
  {
    "id": "mist",
    "name": "Mist",
    "role": "MAGIC",
    "attack_type": "MAGIC",
    "base_attack": 1500,
    "base_defense": 571,
    "base_hp": 3326,
    "base_speed": 29,
    "transcend_primary": "ATK",
    "star4_bonus": "EFF",
    "grade": "LEGEND"
  },
  {
    "id": "silvesta",
    "name": "Silvesta",
    "role": "MAGIC",
    "attack_type": "MAGIC",
    "base_attack": 1500,
    "base_defense": 571,
    "base_hp": 3326,
    "base_speed": 29,
    "transcend_primary": "ATK",
    "star4_bonus": "CR",
    "grade": "LEGEND"
  },
  {
    "id": "clemyth",
    "name": "Clemyth",
    "role": "MAGIC",
    "attack_type": "MAGIC",
    "base_attack": 1500,
    "base_defense": 571,
    "base_hp": 3326,
    "base_speed": 29,
    "transcend_primary": "ATK",
    "star4_bonus": "CR",
    "grade": "LEGEND"
  },
  {
    "id": "aris",
    "name": "Aris",
    "role": "MAGIC",
    "attack_type": "MAGIC",
    "base_attack": 1500,
    "base_defense": 571,
    "base_hp": 3326,
    "base_speed": 29,
    "transcend_primary": "ATK",
    "star4_bonus": "CR",
    "grade": "LEGEND"
  },
  {
    "id": "eileene",
    "name": "Eileene",
    "role": "MAGIC",
    "attack_type": "MAGIC",
    "base_attack": 1500,
    "base_defense": 571,
    "base_hp": 3326,
    "base_speed": 29,
    "transcend_primary": "ATK",
    "star4_bonus": "CR",
    "grade": "LEGEND"
  },
  {
    "id": "jury",
    "name": "Jury",
    "role": "MAGIC",
    "attack_type": "MAGIC",
    "base_attack": 1500,
    "base_defense": 571,
    "base_hp": 3326,
    "base_speed": 29,
    "transcend_primary": "ATK",
    "star4_bonus": "EFF",
    "grade": "LEGEND"
  },
  {
    "id": "nix",
    "name": "Nix",
    "role": "MAGIC",
    "attack_type": "MAGIC",
    "base_attack": 1389,
    "base_defense": 533,
    "base_hp": 3174,
    "base_speed": 25,
    "transcend_primary": "ATK",
    "star4_bonus": "CR",
    "grade": "RARE"
  },
  {
    "id": "espada",
    "name": "Espada",
    "role": "MAGIC",
    "attack_type": "MAGIC",
    "base_attack": 1389,
    "base_defense": 533,
    "base_hp": 3174,
    "base_speed": 25,
    "transcend_primary": "ATK",
    "star4_bonus": "CR",
    "grade": "RARE"
  },
  {
    "id": "velika",
    "name": "Velika",
    "role": "MAGIC",
    "attack_type": "MAGIC",
    "base_attack": 1389,
    "base_defense": 533,
    "base_hp": 3174,
    "base_speed": 25,
    "transcend_primary": "ATK",
    "star4_bonus": "CR",
    "grade": "RARE"
  },
  {
    "id": "ariel",
    "name": "Ariel",
    "role": "MAGIC",
    "attack_type": "MAGIC",
    "base_attack": 1389,
    "base_defense": 533,
    "base_hp": 3174,
    "base_speed": 25,
    "transcend_primary": "ATK",
    "star4_bonus": "CR",
    "grade": "RARE"
  },
  {
    "id": "sylvia",
    "name": "Sylvia",
    "role": "MAGIC",
    "attack_type": "MAGIC",
    "base_attack": 1389,
    "base_defense": 533,
    "base_hp": 3174,
    "base_speed": 25,
    "transcend_primary": "ATK",
    "star4_bonus": "EFF",
    "grade": "RARE"
  },
  {
    "id": "alice",
    "name": "Alice",
    "role": "MAGIC",
    "attack_type": "MAGIC",
    "base_attack": 1389,
    "base_defense": 533,
    "base_hp": 3174,
    "base_speed": 25,
    "transcend_primary": "ATK",
    "star4_bonus": "CR",
    "grade": "RARE"
  },
  {
    "id": "ellin",
    "name": "Ellin",
    "role": "MAGIC",
    "attack_type": "MAGIC",
    "base_attack": 1389,
    "base_defense": 533,
    "base_hp": 3174,
    "base_speed": 25,
    "transcend_primary": "ATK",
    "star4_bonus": "CR",
    "grade": "RARE"
  },
  {
    "id": "yuri",
    "name": "Yuri",
    "role": "MAGIC",
    "attack_type": "MAGIC",
    "base_attack": 1389,
    "base_defense": 533,
    "base_hp": 3174,
    "base_speed": 25,
    "transcend_primary": "ATK",
    "star4_bonus": "EFF",
    "grade": "RARE"
  },
  {
    "id": "sarah",
    "name": "Sarah",
    "role": "MAGIC",
    "attack_type": "MAGIC",
    "base_attack": 1389,
    "base_defense": 533,
    "base_hp": 3174,
    "base_speed": 25,
    "transcend_primary": "ATK",
    "star4_bonus": "EFF",
    "grade": "RARE"
  },
  {
    "id": "ellie",
    "name": "Ellie",
    "role": "MAGIC",
    "attack_type": "MAGIC",
    "base_attack": 1389,
    "base_defense": 533,
    "base_hp": 3174,
    "base_speed": 25,
    "transcend_primary": "ATK",
    "star4_bonus": "CR",
    "grade": "RARE"
  },
  {
    "id": "daisy",
    "name": "Daisy",
    "role": "MAGIC",
    "attack_type": "MAGIC",
    "base_attack": 1389,
    "base_defense": 533,
    "base_hp": 3174,
    "base_speed": 25,
    "transcend_primary": "ATK",
    "star4_bonus": "CR",
    "grade": "RARE"
  },
    {
    "id": "gellidus",
    "name": "Gellidus",
    "role": "UNIVERSAL",
    "attack_type": "ATTACK",
    "base_attack": 1306,
    "base_defense": 659,
    "base_hp": 3693,
    "base_speed": 25,
    "transcend_primary": "DEF",
    "star4_bonus": "RED",
    "grade": "LEGEND"
  },
  {
    "id": "mist",
    "name": "Mist",
    "role": "UNIVERSAL",
    "attack_type": "MAGIC",
    "base_attack": 1306,
    "base_defense": 659,
    "base_hp": 3693,
    "base_speed": 25,
    "transcend_primary": "ATK",
    "star4_bonus": "EFF",
    "grade": "LEGEND"
  },
  {
    "id": "nia",
    "name": "Nia",
    "role": "UNIVERSAL",
    "attack_type": "MAGIC",
    "base_attack": 1306,
    "base_defense": 659,
    "base_hp": 3693,
    "base_speed": 25,
    "transcend_primary": "ATK",
    "star4_bonus": "EFF",
    "grade": "LEGEND"
  },
  {
    "id": "chancellor",
    "name": "Chancellor",
    "role": "UNIVERSAL",
    "attack_type": "ATTACK",
    "base_attack": 1306,
    "base_defense": 659,
    "base_hp": 3693,
    "base_speed": 25,
    "transcend_primary": "DEF",
    "star4_bonus": "RED",
    "grade": "LEGEND"
  },
  {
    "id": "sieg",
    "name": "Sieg",
    "role": "UNIVERSAL",
    "attack_type": "ATTACK",
    "base_attack": 1306,
    "base_defense": 659,
    "base_hp": 3693,
    "base_speed": 25,
    "transcend_primary": "ATK",
    "star4_bonus": "CR",
    "grade": "LEGEND"
  },
  {
    "id": "bai_jiao",
    "name": "Bai Jiao",
    "role": "UNIVERSAL",
    "attack_type": "MAGIC",
    "base_attack": 1306,
    "base_defense": 659,
    "base_hp": 3693,
    "base_speed": 25,
    "transcend_primary": "ATK",
    "star4_bonus": "CR",
    "grade": "LEGEND"
  },
  {
    "id": "guan_yu",
    "name": "Guan Yu",
    "role": "UNIVERSAL",
    "attack_type": "ATTACK",
    "base_attack": 1306,
    "base_defense": 659,
    "base_hp": 3693,
    "base_speed": 25,
    "transcend_primary": "ATK",
    "star4_bonus": "WK",
    "grade": "LEGEND"
  },
  {
    "id": "elysia",
    "name": "Elysia",
    "role": "UNIVERSAL",
    "attack_type": "ATTACK",
    "base_attack": 1306,
    "base_defense": 659,
    "base_hp": 3693,
    "base_speed": 25,
    "transcend_primary": "ATK",
    "star4_bonus": "RED",
    "grade": "LEGEND"
  },
  {
    "id": "pallanus",
    "name": "Pallanus",
    "role": "UNIVERSAL",
    "attack_type": "ATTACK",
    "base_attack": 1306,
    "base_defense": 659,
    "base_hp": 3693,
    "base_speed": 25,
    "transcend_primary": "ATK",
    "star4_bonus": "RED",
    "grade": "LEGEND"
  },
  {
    "id": "sun_wukong",
    "name": "Sun Wukong",
    "role": "UNIVERSAL",
    "attack_type": "MAGIC",
    "base_attack": 1306,
    "base_defense": 659,
    "base_hp": 3693,
    "base_speed": 25,
    "transcend_primary": "ATK",
    "star4_bonus": "RED",
    "grade": "LEGEND"
  },
  {
    "id": "trude",
    "name": "Trude",
    "role": "UNIVERSAL",
    "attack_type": "ATTACK",
    "base_attack": 1306,
    "base_defense": 659,
    "base_hp": 3693,
    "base_speed": 25,
    "transcend_primary": "ATK",
    "star4_bonus": "WK",
    "grade": "LEGEND"
  },
  {
    "id": "karma",
    "name": "Karma",
    "role": "UNIVERSAL",
    "attack_type": "MAGIC",
    "base_attack": 1306,
    "base_defense": 659,
    "base_hp": 3693,
    "base_speed": 25,
    "transcend_primary": "DEF",
    "star4_bonus": "RED",
    "grade": "LEGEND"
  },
  {
    "id": "eileene",
    "name": "Eileene",
    "role": "UNIVERSAL",
    "attack_type": "ATTACK",
    "base_attack": 1306,
    "base_defense": 659,
    "base_hp": 3693,
    "base_speed": 25,
    "transcend_primary": "ATK",
    "star4_bonus": "EFF",
    "grade": "LEGEND"
  },
  {
    "id": "rachel",
    "name": "Rachel",
    "role": "UNIVERSAL",
    "attack_type": "ATTACK",
    "base_attack": 1306,
    "base_defense": 659,
    "base_hp": 3693,
    "base_speed": 25,
    "transcend_primary": "ATK",
    "star4_bonus": "WK",
    "grade": "LEGEND"
  },
  {
    "id": "spike",
    "name": "Spike",
    "role": "UNIVERSAL",
    "attack_type": "ATTACK",
    "base_attack": 1306,
    "base_defense": 659,
    "base_hp": 3693,
    "base_speed": 25,
    "transcend_primary": "DEF",
    "star4_bonus": "RED",
    "grade": "LEGEND"
  },
  {
    "id": "jave",
    "name": "Jave",
    "role": "UNIVERSAL",
    "attack_type": "ATTACK",
    "base_attack": 1306,
    "base_defense": 659,
    "base_hp": 3693,
    "base_speed": 25,
    "transcend_primary": "ATK",
    "star4_bonus": "RED",
    "grade": "LEGEND"
  },
  {
    "id": "kris",
    "name": "Kris",
    "role": "UNIVERSAL",
    "attack_type": "ATTACK",
    "base_attack": 1306,
    "base_defense": 659,
    "base_hp": 3693,
    "base_speed": 25,
    "transcend_primary": "ATK",
    "star4_bonus": "EFF",
    "grade": "LEGEND"
  },
  {
    "id": "ace",
    "name": "Ace",
    "role": "UNIVERSAL",
    "attack_type": "ATTACK",
    "base_attack": 1306,
    "base_defense": 659,
    "base_hp": 3693,
    "base_speed": 25,
    "transcend_primary": "ATK",
    "star4_bonus": "CR",
    "grade": "LEGEND"
  },
  {
    "id": "victoria",
    "name": "Victoria",
    "role": "UNIVERSAL",
    "attack_type": "ATTACK",
    "base_attack": 1238,
    "base_defense": 616,
    "base_hp": 3529,
    "base_speed": 21,
    "transcend_primary": "DEF",
    "star4_bonus": "RED",
    "grade": "RARE"
  },
  {
    "id": "asura",
    "name": "Asura",
    "role": "UNIVERSAL",
    "attack_type": "ATTACK",
    "base_attack": 1238,
    "base_defense": 616,
    "base_hp": 3529,
    "base_speed": 21,
    "transcend_primary": "ATK",
    "star4_bonus": "RED",
    "grade": "RARE"
  },
  {
    "id": "lania",
    "name": "Lania",
    "role": "UNIVERSAL",
    "attack_type": "MAGIC",
    "base_attack": 1238,
    "base_defense": 616,
    "base_hp": 3529,
    "base_speed": 21,
    "transcend_primary": "ATK",
    "star4_bonus": "WK",
    "grade": "RARE"
  },

  {
    "id": "rudy",
    "name": "Rudy",
    "role": "DEFENSE",
    "attack_type": "ATTACK",
    "base_attack": 727,
    "base_defense": 892,
    "base_hp": 4825,
    "base_speed": 19,
    "transcend_primary": "DEF",
    "star4_bonus": "BLK",
    "grade": "LEGEND"
  },
  {
    "id": "aquila",
    "name": "Aquila",
    "role": "DEFENSE",
    "attack_type": "ATTACK",
    "base_attack": 727,
    "base_defense": 892,
    "base_hp": 4825,
    "base_speed": 19,
    "transcend_primary": "DEF",
    "star4_bonus": "RED",
    "grade": "LEGEND"
  },
  {
    "id": "radgrid",
    "name": "Radgrid",
    "role": "DEFENSE",
    "attack_type": "ATTACK",
    "base_attack": 727,
    "base_defense": 892,
    "base_hp": 4825,
    "base_speed": 19,
    "transcend_primary": "DEF",
    "star4_bonus": "BLK",
    "grade": "LEGEND"
  },
  {
    "id": "aragon",
    "name": "Aragon",
    "role": "DEFENSE",
    "attack_type": "ATTACK",
    "base_attack": 727,
    "base_defense": 892,
    "base_hp": 4825,
    "base_speed": 19,
    "transcend_primary": "DEF",
    "star4_bonus": "BLK",
    "grade": "LEGEND"
  },
  {
    "id": "rook",
    "name": "Rook",
    "role": "DEFENSE",
    "attack_type": "ATTACK",
    "base_attack": 727,
    "base_defense": 892,
    "base_hp": 4825,
    "base_speed": 19,
    "transcend_primary": "DEF",
    "star4_bonus": "BLK",
    "grade": "LEGEND"
  },
  {
    "id": "knox",
    "name": "Knox",
    "role": "DEFENSE",
    "attack_type": "ATTACK",
    "base_attack": 727,
    "base_defense": 892,
    "base_hp": 4825,
    "base_speed": 19,
    "transcend_primary": "DEF",
    "star4_bonus": "BLK",
    "grade": "LEGEND"
  },
  {
    "id": "hellenia",
    "name": "Hellenia",
    "role": "DEFENSE",
    "attack_type": "ATTACK",
    "base_attack": 727,
    "base_defense": 892,
    "base_hp": 4825,
    "base_speed": 19,
    "transcend_primary": "DEF",
    "star4_bonus": "BLK",
    "grade": "RARE"
  },
  {
    "id": "evan",
    "name": "Evan",
    "role": "DEFENSE",
    "attack_type": "ATTACK",
    "base_attack": 704,
    "base_defense": 818,
    "base_hp": 4572,
    "base_speed": 16,
    "transcend_primary": "DEF",
    "star4_bonus": "BLK",
    "grade": "RARE"
  },
  {
    "id": "li",
    "name": "Li",
    "role": "DEFENSE",
    "attack_type": "ATTACK",
    "base_attack": 704,
    "base_defense": 818,
    "base_hp": 4572,
    "base_speed": 16,
    "transcend_primary": "DEF",
    "star4_bonus": "BLK",
    "grade": "RARE"
  },
  {
    "id": "yoo_jinho",
    "name": "Yoo Jinho",
    "role": "DEFENSE",
    "attack_type": "ATTACK",
    "base_attack": 704,
    "base_defense": 818,
    "base_hp": 4572,
    "base_speed": 16,
    "transcend_primary": "DEF",
    "star4_bonus": "BLK",
    "grade": "RARE"
  },
  {
    "id": "rahkun",
    "name": "Rahkun",
    "role": "DEFENSE",
    "attack_type": "ATTACK",
    "base_attack": 704,
    "base_defense": 818,
    "base_hp": 4572,
    "base_speed": 16,
    "transcend_primary": "DEF",
    "star4_bonus": "BLK",
    "grade": "RARE"
  },
    {
    "id": "rosie",
    "name": "Rosie",
    "role": "SUPPORT",
    "attack_type": "MAGIC",
    "base_attack": 1095,
    "base_defense": 675,
    "base_hp": 4458,
    "base_speed": 19,
    "transcend_primary": "DEF",
    "star4_bonus": "RED",
    "grade": "LEGEND"
  },
  {
    "id": "platin",
    "name": "Platin",
    "role": "SUPPORT",
    "attack_type": "MAGIC",
    "base_attack": 1095,
    "base_defense": 675,
    "base_hp": 4458,
    "base_speed": 19,
    "transcend_primary": "DEF",
    "star4_bonus": "RED",
    "grade": "LEGEND"
  },
  {
    "id": "biscuit",
    "name": "Biscuit",
    "role": "SUPPORT",
    "attack_type": "MAGIC",
    "base_attack": 1095,
    "base_defense": 675,
    "base_hp": 4458,
    "base_speed": 19,
    "transcend_primary": "DEF",
    "star4_bonus": "RED",
    "grade": "LEGEND"
  },
  {
    "id": "alice",
    "name": "Alice",
    "role": "SUPPORT",
    "attack_type": "MAGIC",
    "base_attack": 1095,
    "base_defense": 675,
    "base_hp": 4458,
    "base_speed": 19,
    "transcend_primary": "DEF",
    "star4_bonus": "RED",
    "grade": "LEGEND"
  },
  {
    "id": "lina",
    "name": "Lina",
    "role": "SUPPORT",
    "attack_type": "MAGIC",
    "base_attack": 1095,
    "base_defense": 675,
    "base_hp": 4458,
    "base_speed": 19,
    "transcend_primary": "DEF",
    "star4_bonus": "RED",
    "grade": "LEGEND"
  },
  {
    "id": "orly",
    "name": "Orly",
    "role": "SUPPORT",
    "attack_type": "MAGIC",
    "base_attack": 1095,
    "base_defense": 675,
    "base_hp": 4458,
    "base_speed": 19,
    "transcend_primary": "DEF",
    "star4_bonus": "RED",
    "grade": "LEGEND"
  },
  {
    "id": "diaochan",
    "name": "Diaochan",
    "role": "SUPPORT",
    "attack_type": "MAGIC",
    "base_attack": 1095,
    "base_defense": 675,
    "base_hp": 4458,
    "base_speed": 19,
    "transcend_primary": "DEF",
    "star4_bonus": "RED",
    "grade": "LEGEND"
  },
  {
    "id": "karin",
    "name": "Karin",
    "role": "SUPPORT",
    "attack_type": "MAGIC",
    "base_attack": 1035,
    "base_defense": 632,
    "base_hp": 4248,
    "base_speed": 16,
    "transcend_primary": "DEF",
    "star4_bonus": "RED",
    "grade": "RARE"
  },
  {
    "id": "karon",
    "name": "Karon",
    "role": "SUPPORT",
    "attack_type": "MAGIC",
    "base_attack": 1035,
    "base_defense": 632,
    "base_hp": 4248,
    "base_speed": 16,
    "transcend_primary": "DEF",
    "star4_bonus": "RED",
    "grade": "RARE"
  },
  {
    "id": "lucy",
    "name": "Lucy",
    "role": "SUPPORT",
    "attack_type": "MAGIC",
    "base_attack": 1035,
    "base_defense": 632,
    "base_hp": 4248,
    "base_speed": 16,
    "transcend_primary": "DEF",
    "star4_bonus": "RED",
    "grade": "RARE"
  },
  {
    "id": "yui",
    "name": "Yui",
    "role": "SUPPORT",
    "attack_type": "MAGIC",
    "base_attack": 1035,
    "base_defense": 632,
    "base_hp": 4248,
    "base_speed": 16,
    "transcend_primary": "DEF",
    "star4_bonus": "RED",
    "grade": "RARE"
  },
  {
    "id": "chloe",
    "name": "Chloe",
    "role": "SUPPORT",
    "attack_type": "MAGIC",
    "base_attack": 1035,
    "base_defense": 632,
    "base_hp": 4248,
    "base_speed": 16,
    "transcend_primary": "DEF",
    "star4_bonus": "RED",
    "grade": "RARE"
  },
  {
    "id": "lee_joohee",
    "name": "Lee Joohee",
    "role": "SUPPORT",
    "attack_type": "MAGIC",
    "base_attack": 1035,
    "base_defense": 632,
    "base_hp": 4248,
    "base_speed": 16,
    "transcend_primary": "DEF",
    "star4_bonus": "RED",
    "grade": "RARE"
  },
  {
    "id": "sarah",
    "name": "Sarah",
    "role": "SUPPORT",
    "attack_type": "MAGIC",
    "base_attack": 1035,
    "base_defense": 632,
    "base_hp": 4248,
    "base_speed": 16,
    "transcend_primary": "DEF",
    "star4_bonus": "RED",
    "grade": "RARE"
  }
];